<?php $this->headTitle($this->translate('About')); ?>
<?php $this->layout()->searchbox = false; ?>

<div class="logo-img-center">
  <a href="<?= $this->url('home') ?>"><img class="img-responsive" src="<?= $this->imageLink('oasisbr.png'); ?>" alt="Logo do OasisBR" /></a>
</div>
<div class="about">

  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <h2> <?= $this->transEsc('about title'); ?> </h2>
        <p>
          <?= $this->transEsc('about p1'); ?>
        </p>
        <p>
          <?= $this->transEsc('about p2'); ?>
        </p>
        <p>
          <?= $this->transEsc('about p3'); ?>
          <a target="_blank" href="https://www.rcaap.pt"> <?= $this->transEsc('about link rcaap'); ?></a>
        </p>
      </div>
    </div>
  </div>

  <div class="row objectives">
    <div class="col-md-12">
      <div class="card">
        <h2> <a data-toggle="collapse" class="btn-collapse" href="#objetivos" aria-expanded="true" aria-controls="footwear">
            <?= $this->transEsc('Goals'); ?>
          </a>
        </h2>
        <div class="collapse in" id="objetivos">
          <ul>
            <li>
              <?= $this->transEsc('goal 1'); ?>
            </li>
            <li>
              <?= $this->transEsc('goal 2'); ?>
            </li>
            <li>
              <?= $this->transEsc('goal 3'); ?>
            </li>
            <li>
              <?= $this->transEsc('goal 4'); ?></li>
            <li>
              <?= $this->transEsc('goal 5'); ?></li>
            <li>
              <?= $this->transEsc('goal 6'); ?>
            </li>
            <li>
              <?= $this->transEsc('goal 7'); ?>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 network-flow" id="network-flow">
      <div class="card">
        <h2> <a data-toggle="collapse" class="btn-collapse" href="#fluxo" aria-expanded="true" aria-controls="footwear">
            <?= $this->transEsc('Oasisbr information flow'); ?>
          </a>
        </h2>
        <div class="collapse in" id="fluxo">
          <p> <?= $this->transEsc('flow p1'); ?></p>
          <p>
            <?= $this->transEsc('flow p2'); ?>
            <a target="_blank" href="https://www.rcaap.pt"> <?= $this->transEsc('about link rcaap'); ?></a>
            <?= $this->transEsc('flow p3'); ?>
            <a target="_blank" href="https://www.lareferencia.info/pt"> <?= $this->transEsc('La Referencia'); ?></a>
            <?= $this->transEsc('flow p4'); ?>
            <a target="_blank" href="https://www.openaire.eu/">OpenAIRE</a>
            .
          </p>
          <p> <?= $this->transEsc('flow p5'); ?></p>
        </div>
      </div>
    </div>
  </div>

  <div class="row ">
    <div class="col-md-12">
      <div class="card">
        <h2> <?= $this->transEsc('Criteria for collecting information sources'); ?></h2>
        <h3> <a data-toggle="collapse" class="btn-collapse collapsed" href="#monographs" aria-expanded="false" aria-controls="footwear">
            <?= $this->transEsc('Digital libraries of monographs'); ?></a>
        </h3>
        <div class="collapse" id="monographs">
          <ul>
            <li>
              <?= $this->transEsc('dlm p1'); ?>
              <a href="https://www.openarchives.org/pmh" target="_blank" rel="noopener noreferrer">
                <?= $this->transEsc('dlm  OAI link'); ?>
              </a>
              <?= $this->transEsc('dlm p2'); ?>
            </li>
            <li>
              <?= $this->transEsc('dlm p3'); ?>
            </li>
            <li>
              <?= $this->transEsc('dlm p4'); ?>
              <a href="https://dublincore.org" target="_blank" rel="noopener noreferrer">
                <?= $this->transEsc('Dublin Core'); ?>
              </a>
              <?= $this->transEsc('dlm p5'); ?>
            </li>
            <li>
              <?= $this->transEsc('dlm p6'); ?>
            </li>
            <li>
              <?= $this->transEsc('dlm p7'); ?>
            </li>
            <li>
              <?= $this->transEsc('dlm p8'); ?>
            </li>
            <li>
              <?= $this->transEsc('dlm p9'); ?>
            </li>
            <li>
              <?= $this->transEsc('dlm p10'); ?>
            </li>
            <li>
              <?= $this->transEsc('dlm p11'); ?>
            </li>
            <li>
              <?= $this->transEsc('dlm p12'); ?>
            </li>
            <li>
              <?= $this->transEsc('dlm p13'); ?>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

</div>